# .golangci.yml
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - dist
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

  disable:
    - depguard
    - gochecknoglobals
    - godot
    - godox
    - goerr113
    - maligned
    - nestif
    - prealloc
    - testpackage
    - wrapcheck

linters-settings:
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mjmorales/mac-daemon-control)
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: github.com/mjmorales/mac-daemon-control
  
  golint:
    min-confidence: 0
  
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return
  
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/rs/zerolog/zerolog.Event).Msgf
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  revive:
    confidence: 0

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl
    
    - path: cmd/
      linters:
        - gochecknoinits
    
    - linters:
        - stylecheck
      text: "ST1000:"

  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info