# Defines the configuration version.
# The only possible value is "2".
version: "2"

# Options for analysis running.
run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # Default: 0 (disabled)
  timeout: 5m

  # Include test files or not.
  # Default: true
  tests: true

  # The mode used to evaluate relative paths.
  # Default: cfg
  relative-path-mode: gomod

# Linters configuration.
linters:
  # Disable all linters that are not explicitly enabled.
  disable-all: true
  
  # Enable specific linters.
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - copyloopvar  # replaces exportloopref in newer versions
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

# All available settings of specific linters.
linters-settings:
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 100

  funlen:
    # Checks the number of lines in a function.
    # Default: 60
    lines: 100
    # Checks the number of statements in a function.
    # Default: 40
    statements: 50

  goconst:
    # Minimal length of string constant.
    # Default: 3
    min-len: 2
    # Minimum occurrences of constant string count to trigger issue.
    # Default: 3
    min-occurrences: 2

  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 15


  lll:
    # Max line length, lines longer will be reported.
    # Default: 120
    line-length: 140

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    locale: US

  revive:
    # Sets the default severity.
    # Default: warning
    severity: warning

# Formatters configuration.
formatters:
  # Enable specific formatters.
  enable:
    - gofmt
    - goimports
  
  # Formatters settings.
  settings:
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/mjmorales/mac-daemon-control

# Issues configuration.
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source.
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen
        - dupl
    # Exclude gochecknoinits from cmd/ files
    - path: cmd/
      linters:
        - gochecknoinits